name: Bug Report
description: File a report to help us improve
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How do we trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs Actual Behavior
      description: What did you expect to happen, and what actually happened?
  - type: textarea
    id: environment
    attributes:
      label: Environment Info
      description: OS, Browser, Version, etc.
