"""Added embedding column

Revision ID: 1341ad5c25ac
Revises: d22ceaa97b2d
Create Date: 2025-12-10 22:52:14.530773

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1341ad5c25ac"
down_revision = "d22ceaa97b2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("embedding", sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("embedding")

    # ### end Alembic commands ###
