"""Add is_deleted field to Item model to allow soft-delete

Revision ID: 3248b12265fe
Revises: c393b869e302
Create Date: 2026-01-02 21:56:05.377606

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3248b12265fe"
down_revision = "c393b869e302"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    # ### end Alembic commands ###
