"""Remove payment_method from orders

Revision ID: 4c0695acc2b0
Revises: d22ceaa97b2d
Create Date: 2025-12-10 21:41:10.569429

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c0695acc2b0"
down_revision = "d22ceaa97b2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("payment_method")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("payment_method", sa.VARCHAR(length=50), nullable=False)
        )

    # ### end Alembic commands ###
