"""Enforce required item fields

Revision ID: 92f614413327
Revises: 3248b12265fe
Create Date: 2026-01-17 13:20:22.409199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f614413327'
down_revision = '3248b12265fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('seller_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('item_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('seller_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
