"""Update Item column name from image_url to item_image

Revision ID: c393b869e302
Revises: f8669302c435
Create Date: 2025-12-19 04:03:26.220479

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c393b869e302"
down_revision = "f8669302c435"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("item_image", sa.String(length=255), nullable=True)
        )
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_url", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_column("item_image")

    # ### end Alembic commands ###
